### ISSUE TITLE
Method changed to static access producing errors report in Icy.

### ISSUE THREAD

**Issue by Stephane-D** [clij/clicy#2]
Just to let you know, i just received this report in Icy.
Normally you should have received it but sometime for _bundled_ plugin it doesn't recover properly author information:

> Icy Version 2.0.3.0
> Java(TM) SE Runtime Environment 1.8.0_202-b08 (64 bit)
> Running on Windows 10 10.0 (amd64)
> Max java memory : 16.9 GB
> 
> Bundled plugin (could not retrieve origin plugin)
> 
> Comment:
> Please type here your comment
> 
> java.lang.IncompatibleClassChangeError: Expecting non-static method net.haesleinhuepf.clijx.advancedfilters.SubtractBackground3D.asFloat(Ljava/lang/Object;)Ljava/lang/Float;
> at net.haesleinhuepf.clijx.advancedfilters.SubtractBackground3D.executeCL(SubtractBackground3D.java:25)
> at plugins.haesleinhuepf.AbstractCLIJxBlock.run(AbstractCLIJxBlock.java:154)
> at plugins.haesleinhuepf.buttons.SubtractBackground3D.execute(SubtractBackground3D.java:57)
> at plugins.adufour.ezplug.EzPlug.run(EzPlug.java:439)
> at java.lang.Thread.run(Thread.java:748)

Looks like you changed the prototype of a function (non static to static).

**Comment by haesleinhuepf** [comment]
Hey @Stephane-D,

thanks for the report. I assume this bug is gone as all jars have been rebuild. On the other hand I couldn't reproduce it. Please reopen this issue, if you meet the error message again.

Thanks for all your support!

Cheers,
Robert

**Comment by Stephane-D** [comment]
Hi @haesleinhuepf 

It seems ok, i never got the message anymore :)
