### ISSUE TITLE
Plugin documentation - InstallClicyToolbar

### ISSUE THREAD

**Issue by marionlouveaux** [clij/clicy#3]
Hi!

The **plugin InstallClicyToolbar** is great but unfortunately not documented yet. Especially, when clicking on "?" on the plugin window, or right clicking on it in the search bar it does not link to any documentation on the Icy website.
Would it be possible to add a new page for this plugin with some explanations on its function?
Many thanks in advance!

Best regards,
Marion

**Comment by haesleinhuepf** [comment]
Hey Marion @marionlouveaux ,

thanks for testing clicy! ❤️ 

The suggestion is really great. Do you by chance know how I can control what happens if someone clicks on the "Help" button? I searchd the [EzPlug documentation](https://github.com/DrDaleks/adufour.github.com/tree/master/EzPlug/doc) but feel a bit lost...

Any hint is appreciated. Thanks!

Cheers,
Robert

**Comment by marionlouveaux** [comment]
Hi Robert,
You're welcome! :)
I'll ask my colleagues and make a note to add it to the documentation on the Icy website. Thanks for the feedback ;)
Cheers,
Marion

**Comment by marionlouveaux** [comment]
Hi Robert,

So, after asking my colleagues Stephane and Daniel, it seems that what I observed (clicking on the "Help" button does not launch the online help page) comes from the fact that the plugin InstallClicyToolbar is bundled to the Clicy plugin.
They recommend to separate the plugin InstallClicyToolbar from the Clicy plugin and in general they don't recommend using bundled plugins. Separating the two plugins should hopefully solve this issue.
Since it is a rather technical topic, I would suggest that you open a thread on the image.sc forum if you have more questions. I am sure this is of interest for other Icy plugins developers. 

Cheers,
Marion

**Comment by haesleinhuepf** [comment]
Alright, I'm closing this issue here as we continue the discussion on image.sc:
https://forum.image.sc/t/help-button-issue-with-bundled-plugins-in-icy/38780
