### ISSUE TITLE
Broken link on the clicy website

### ISSUE THREAD

**Issue by marionlouveaux** [clij/clicy#5]
Hi!
I found a broken link on the clicy website https://clij.github.io/clicy/: "Also feel free to copy paste from the **CLIJ2 documentation**, it contains Icy code snippets."
Best regards,
Marion

**Comment by haesleinhuepf** [comment]
Hey Marion @marionlouveaux ,

this one was easy to fix. :-) Thanks for spotting it!

Cheers,
Robert
