### ISSUE TITLE
Block "centroids of labels" gives no output

### ISSUE THREAD

**Issue by marionlouveaux** [clij/clicy#7]
Hi!
I noticed that the protocol block "centroids of labels" gives no output (one cannot access the pointlist), is that normal?
Many thanks in advance!
Best regards,
Marion

**Comment by haesleinhuepf** [comment]
Hey Marion @marionlouveaux ,

this was a bug in CLIJ2, after regenerating the clIcy API, it should have an image (pointlist) as output.

Thanks for spotting this one!

Cheers,
Robert

**Comment by marionlouveaux** [comment]
Hi Robert,

Thank you!!

Cheers,
Marion
